
apiVersion: apps/v1
kind: Deployment
metadata:
  name: revent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: revent
  template:
    metadata:
      labels:
        app: revent
    spec:
      containers:
      - name: revent
        image: pius20/revent:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: revent
spec:
  selector:
    app: revent
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: revent-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: taskmanager.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: revent
            port:
              number: 80
